-- Migration: add_payment_module
-- Generated by prisma migrate diff (applied via resolve)
-- Tables already exist in DB via prisma db push; this file documents the schema.

-- CreateEnum
CREATE TYPE "FinancialEntryStatus" AS ENUM ('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED');

-- CreateEnum
CREATE TYPE "FinancialEntryType" AS ENUM ('RECEIVABLE', 'PAYABLE');

-- CreateEnum
CREATE TYPE "PaymentAccountType" AS ENUM ('CHECKING', 'SAVINGS', 'CASH', 'DIGITAL');

-- CreateEnum
CREATE TYPE "FinancialCategoryType" AS ENUM ('REVENUE', 'EXPENSE', 'COST');

-- CreateTable
CREATE TABLE "payment_bank_accounts" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "bank_name" TEXT,
    "bank_code" TEXT,
    "agency" TEXT,
    "account" TEXT,
    "type" "PaymentAccountType" NOT NULL DEFAULT 'CHECKING',
    "balance" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "color" TEXT DEFAULT '#1E90FF',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "payment_bank_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payment_categories" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" "FinancialCategoryType" NOT NULL,
    "color" TEXT DEFAULT '#1E90FF',
    "icon" TEXT,
    "parent_id" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "payment_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payment_cost_centers" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "payment_cost_centers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payment_contacts" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "document" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "contact_type" TEXT NOT NULL DEFAULT 'BOTH',
    "notes" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "credit_limit" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "payment_contacts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payment_access" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "is_authorized" BOOLEAN NOT NULL DEFAULT false,
    "phone" TEXT,
    "authorized_by_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "payment_access_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payment_entries" (
    "id" TEXT NOT NULL,
    "organization_id" TEXT NOT NULL,
    "type" "FinancialEntryType" NOT NULL,
    "status" "FinancialEntryStatus" NOT NULL DEFAULT 'PENDING',
    "description" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "paid_amount" INTEGER NOT NULL DEFAULT 0,
    "due_date" TIMESTAMP(3) NOT NULL,
    "paid_at" TIMESTAMP(3),
    "competence_date" TIMESTAMP(3),
    "document_number" TEXT,
    "notes" TEXT,
    "attachment_url" TEXT,
    "category_id" TEXT,
    "cost_center_id" TEXT,
    "contact_id" TEXT,
    "account_id" TEXT,
    "installment_total" INTEGER,
    "installment_current" INTEGER,
    "installment_group_id" TEXT,
    "is_recurring" BOOLEAN NOT NULL DEFAULT false,
    "recurrence_type" TEXT,
    "created_by_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "payment_entries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "payment_bank_accounts_organization_id_idx" ON "payment_bank_accounts"("organization_id");

-- CreateIndex
CREATE INDEX "payment_categories_organization_id_idx" ON "payment_categories"("organization_id");

-- CreateIndex
CREATE INDEX "payment_cost_centers_organization_id_idx" ON "payment_cost_centers"("organization_id");

-- CreateIndex
CREATE INDEX "payment_contacts_organization_id_idx" ON "payment_contacts"("organization_id");

-- CreateIndex
CREATE INDEX "payment_access_organization_id_idx" ON "payment_access"("organization_id");

-- CreateIndex
CREATE UNIQUE INDEX "payment_access_user_id_organization_id_key" ON "payment_access"("user_id", "organization_id");

-- CreateIndex
CREATE INDEX "payment_entries_organization_id_idx" ON "payment_entries"("organization_id");

-- CreateIndex
CREATE INDEX "payment_entries_type_idx" ON "payment_entries"("type");

-- CreateIndex
CREATE INDEX "payment_entries_status_idx" ON "payment_entries"("status");

-- CreateIndex
CREATE INDEX "payment_entries_due_date_idx" ON "payment_entries"("due_date");

-- CreateIndex
CREATE INDEX "payment_entries_contact_id_idx" ON "payment_entries"("contact_id");

-- CreateIndex
CREATE INDEX "payment_entries_category_id_idx" ON "payment_entries"("category_id");

-- CreateIndex
CREATE INDEX "payment_entries_installment_group_id_idx" ON "payment_entries"("installment_group_id");

-- AddForeignKey
ALTER TABLE "payment_bank_accounts" ADD CONSTRAINT "payment_bank_accounts_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_categories" ADD CONSTRAINT "payment_categories_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_categories" ADD CONSTRAINT "payment_categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "payment_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_cost_centers" ADD CONSTRAINT "payment_cost_centers_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_contacts" ADD CONSTRAINT "payment_contacts_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_access" ADD CONSTRAINT "payment_access_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_access" ADD CONSTRAINT "payment_access_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_access" ADD CONSTRAINT "payment_access_authorized_by_id_fkey" FOREIGN KEY ("authorized_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_entries" ADD CONSTRAINT "payment_entries_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_entries" ADD CONSTRAINT "payment_entries_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "payment_categories"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_entries" ADD CONSTRAINT "payment_entries_cost_center_id_fkey" FOREIGN KEY ("cost_center_id") REFERENCES "payment_cost_centers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_entries" ADD CONSTRAINT "payment_entries_contact_id_fkey" FOREIGN KEY ("contact_id") REFERENCES "payment_contacts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_entries" ADD CONSTRAINT "payment_entries_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "payment_bank_accounts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payment_entries" ADD CONSTRAINT "payment_entries_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;
