import type { FC } from "react";
import {
  CommentsIcon,
  NerpIcon,
  CosmicIcon,
  NasaChatIcon,
  SpaceTimeIcon,
  PaymentIcon,
  ForgeIcon,
  LinnkerIcon,
  BoostIcon,
  StarsIcon,
  DemandIcon,
  AstroIcon,
  TaskIcon,
  NBoxIcon,
  TrackingIcon,
  NasaPlannerIcon,
} from "./app-icons";

export type AppStatus = "installed" | "development" | "available";

export interface AppDef {
  id: string;
  name: string;
  byline: string;
  status: AppStatus;
  icon: FC;
  shortDesc: string;
  fullDesc: string;
  category: string;
  integration: string;
  action: "external" | "internal" | "modal";
  href?: string;
  activeUsers?: number | null;
  theme: "purple" | "dark" | "blue";
  sidebarKey?: string;
}

export const APPS: AppDef[] = [
  {
    id: "comments",
    name: "COMMENTS",
    byline: "by NASA®",
    status: "installed",
    icon: CommentsIcon,
    shortDesc: "Automatize respostas nos comentários do Instagram",
    fullDesc:
      "Automatize respostas nos comentários do Instagram e leve o cliente direto para o atendimento certo. Simples, rápido e sem complicação. Mais barato, mais inteligente e integrado ao resto da operação.",
    category: "Engajamento",
    integration: "Instagram",
    action: "external",
    href: "https://comments.nasaex.com/",
    activeUsers: null,
    theme: "purple",
  },
  {
    id: "nerp",
    name: "NERP",
    byline: "by NASA®",
    status: "installed",
    icon: NerpIcon,
    shortDesc: "ERP inteligente integrado ao comercial e atendimento",
    fullDesc:
      "Controle financeiro, loja online, sistema de frente de caixa e dados do negócio no mesmo lugar. Tudo integrado ao comercial e ao atendimento.",
    category: "Gestão",
    integration: "ERP",
    action: "external",
    href: "https://www.nasaerp.com/",
    activeUsers: null,
    theme: "dark",
  },
  {
    id: "cosmic",
    name: "COSMIC",
    byline: "by NASA®",
    status: "installed",
    icon: CosmicIcon,
    shortDesc: "Formulários inteligentes que viram dados estratégicos no CRM",
    fullDesc:
      "Sistema de formulários inteligentes. Cada resposta do cliente vira informação estratégica. O sistema entende o interesse e organiza automaticamente no CRM.",
    category: "CRM",
    integration: "—",
    action: "internal",
    href: "/form",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "cosmic",
  },
  {
    id: "nasachat",
    name: "NASACHAT",
    byline: "by NASA®",
    status: "installed",
    icon: NasaChatIcon,
    shortDesc: "WhatsApp organizado com histórico, CRM e IA integrados",
    fullDesc:
      "O WhatsApp organizado do jeito que deveria ser. Sistema de conversas interno offline. Atenda sem perder histórico, contexto ou oportunidade. Totalmente integrado ao CRM e ao Astro IA.",
    category: "Atendimento",
    integration: "WhatsApp",
    action: "internal",
    href: "/tracking-chat",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "nasachat",
  },
  {
    id: "spacetime",
    name: "SPACETIME",
    byline: "by NASA®",
    status: "installed",
    icon: SpaceTimeIcon,
    shortDesc: "Múltiplas agendas conectadas ao CRM e equipe",
    fullDesc:
      "Quem controla o tempo, controla a venda. Múltiplas agendas conectadas ao atendimento, CRM e equipe. Nada de cliente esquecido ou horário perdido.",
    category: "Agenda",
    integration: "—",
    action: "internal",
    href: "/agendas",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "spacetime",
  },
  {
    id: "forge",
    name: "FORGE",
    byline: "by NASA®",
    status: "installed",
    icon: ForgeIcon,
    shortDesc: "Propostas comerciais e contratos com assinatura digital",
    fullDesc:
      "Crie propostas profissionais, envie contratos digitais e feche negócios mais rápido. Tudo integrado ao CRM.",
    category: "Vendas",
    integration: "Multi-gateway",
    action: "internal",
    href: "/forge",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "forge",
  },
  {
    id: "payment",
    name: "PAYMENT",
    byline: "by NASA®",
    status: "installed",
    icon: PaymentIcon,
    shortDesc: "Gestão financeira: contas, fluxo de caixa, boletos e PIX",
    fullDesc:
      "Hub financeiro central da plataforma. Contas a receber e pagar, fluxo de caixa, DRE, boletos, PIX, notas fiscais e integrações com gateways de pagamento.",
    category: "Financeiro",
    integration: "Asaas · Stripe",
    action: "internal",
    href: "/payment",
    activeUsers: null,
    theme: "blue",
    sidebarKey: "payment",
  },
  {
    id: "linnker",
    name: "LINNKER",
    byline: "by NASA®",
    status: "installed",
    icon: LinnkerIcon,
    shortDesc: "Links personalizados que direcionam, organizam e viram dados",
    fullDesc:
      "Links personalizados que direcionam, organizam e viram dados. Crie páginas de bio estilo Linktree com cards clicáveis, QR codes que capturam leads automaticamente no Tracking, e estatísticas de acesso em tempo real.",
    category: "Marketing",
    integration: "Tracking · Formulários · Agenda · Chat",
    action: "internal",
    href: "/linnker",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "linnker",
  },
  {
    id: "boost",
    name: "BOOST",
    byline: "by NASA®",
    status: "development",
    icon: BoostIcon,
    shortDesc: "Gamificação de vendas com ranking e metas para o time",
    fullDesc:
      "Acompanhe resultados, crie ranking e motive o time. Venda vira jogo. O jogo com regra gera resultado.",
    category: "Vendas",
    integration: "—",
    action: "modal",
    theme: "dark",
  },
  {
    id: "stars",
    name: "STARS",
    byline: "by NASA®",
    status: "installed",
    icon: StarsIcon,
    shortDesc: "Programa de pontos e fidelidade direto no atendimento",
    fullDesc:
      "Cliente lembrado, cliente que volta. Crie programas de pontos direto no atendimento. O cliente acompanha tudo em um painel próprio.",
    category: "Fidelização",
    integration: "—",
    action: "modal",
    activeUsers: null,
    theme: "purple",
  },
  {
    id: "demand",
    name: "DEMAND",
    byline: "by NASA®",
    status: "installed",
    icon: DemandIcon,
    shortDesc: "Painel de controle com tarefas, equipe, clientes e treinamentos",
    fullDesc:
      "O painel de controle da sua operação. Organize tarefas, equipe, clientes e treinamentos em um único lugar. Kanban, listas, automações e mensagens integradas.",
    category: "Gestão",
    integration: "—",
    action: "internal",
    href: "/workspaces",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "workspaces",
  },
  {
    id: "astro",
    name: "ASTRO",
    byline: "by NASA®",
    status: "installed",
    icon: AstroIcon,
    shortDesc: "IA treinada para informar, preparar e quebrar objeções",
    fullDesc:
      "IA treinada para informar, preparar, quebrar objeções e sair de cena. Sem invadir a venda do humano. Sem parecer robô.",
    category: "Inteligência Artificial",
    integration: "—",
    action: "modal",
    activeUsers: null,
    theme: "purple",
  },
  {
    id: "task",
    name: "TASK",
    byline: "by NASA®",
    status: "development",
    icon: TaskIcon,
    shortDesc: "Centralize pedidos, tarefas e chamados com rastreamento",
    fullDesc:
      "Centralize pedidos, tarefas e chamados com rastreamento. Cliente acompanha. Equipe executa.",
    category: "Produtividade",
    integration: "—",
    action: "modal",
    theme: "dark",
  },
  {
    id: "nbox",
    name: "N-BOX",
    byline: "by NASA®",
    status: "installed",
    icon: NBoxIcon,
    shortDesc: "Gestão de documentos, arquivos e links da organização",
    fullDesc:
      "Centralize todos os arquivos, documentos, imagens e links da sua organização em um único lugar. Organize por pastas, busque rapidamente e monitore o uso de armazenamento por plano.",
    category: "Documentos",
    integration: "S3",
    action: "internal",
    href: "/nbox",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "nbox",
  },
  {
    id: "nasa-planner",
    name: "NASA PLANNER",
    byline: "by NASA®",
    status: "installed",
    icon: NasaPlannerIcon,
    shortDesc: "Planeje, crie e execute estratégias de marketing com IA e Mapas Mentais",
    fullDesc:
      "Planejamento estratégico de marketing com IA e Mapas Mentais. Crie múltiplos planners com identidade de marca, Voz & Tom, SWOT e IA integrados. Gere posts para redes sociais, organize ações em mapas mentais (Gantt, diagrama, checklist), acompanhe no calendário e compartilhe com clientes via link. Conectado a todos os apps do NASA.",
    category: "Marketing",
    integration: "Demand · Tracking · N-Box · Spacetime · Nasachat · Insights",
    action: "internal",
    href: "/nasa-planner",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "nasa-planner",
  },
  {
    id: "tracking",
    name: "TRACKING",
    byline: "by NASA®",
    status: "installed",
    icon: TrackingIcon,
    shortDesc: "Rota completa do cliente do primeiro contato à venda",
    fullDesc:
      "Organize atendimentos, vendas, projetos e setores em múltiplos CRMs conectados. Rastreie de onde o cliente veio, o que quer e quando agir.",
    category: "CRM",
    integration: "Multi-CRM",
    action: "internal",
    href: "/tracking",
    activeUsers: null,
    theme: "purple",
    sidebarKey: "tracking",
  },
];
