import type { TourStep } from "./context";

export const NASA_TOUR_STEPS: TourStep[] = [
  {
    id:       "sidebar",
    selector: '[data-tour="sidebar-menu"]',
    title:    "Menu Principal 🗂️",
    message:  "Este é o menu lateral do NASA! Aqui você acessa todos os seus apps: Tracking, Chat, Agenda, Insights e muito mais. Clique em qualquer item para navegar.",
    position: "right",
    padding:  12,
  },
  {
    id:       "nav-tracking",
    selector: '[data-tour="nav-tracking"]',
    title:    "Tracking — Seu CRM 📊",
    message:  "O Tracking é o coração do NASA! Gerencie leads e clientes em colunas visuais (Kanban). Arraste cards, defina responsáveis e feche negócios com mais agilidade.",
    position: "right",
    padding:  8,
    pulse:    true,
  },
  {
    id:       "nav-chat",
    selector: '[data-tour="nav-chat"]',
    title:    "Chat — Central de Mensagens 💬",
    message:  "No Chat você centraliza todas as conversas com clientes em um só lugar. WhatsApp, Instagram, Telegram e muito mais, integrados em uma única caixa de entrada.",
    position: "right",
    padding:  8,
    pulse:    true,
  },
  {
    id:       "nav-integrations",
    selector: '[data-tour="nav-integrations"]',
    title:    "Marketplace de Integrações 🔌",
    message:  "Conecte o NASA com mais de 50 plataformas! WhatsApp Business, Instagram DM, RD Station, Hotmart, Stripe e muito mais. Cada integração expande o poder da sua operação.",
    position: "right",
    padding:  8,
    pulse:    true,
  },
  {
    id:       "nav-agenda",
    selector: '[data-tour="nav-agenda"]',
    title:    "Agenda — Gestão de Tempo 📅",
    message:  "Gerencie seus compromissos, reuniões e follow-ups diretamente na Agenda integrada. Nunca mais perca um contato importante com um cliente.",
    position: "right",
    padding:  8,
  },
  {
    id:       "space-points",
    selector: '[data-tour="space-points"]',
    title:    "Space Points 🚀",
    message:  "Aqui ficam seus Space Points! Cada ação no NASA vale pontos: criar leads, fazer login diário, instalar integrações, completar tarefas. Suba no ranking da equipe!",
    position: "bottom",
    padding:  8,
    pulse:    true,
  },
  {
    id:       "stars",
    selector: '[data-tour="stars"]',
    title:    "Stars ⭐ — Moeda do NASA",
    message:  "Este é seu saldo de Stars — a moeda virtual da plataforma. Use-as para ativar apps, expandir limites de mensagens e acessar recursos premium. Você já ganhou 100 Stars de boas-vindas!",
    position: "bottom",
    padding:  8,
    pulse:    true,
  },
  {
    id:       "astro-button",
    selector: '[data-tour="astro-button"]',
    title:    "Eu sou o ASTRO! 🤖",
    message:  "Este botão sou eu — o ASTRO, sua IA integrada! Pode me chamar sempre que precisar: criar leads, configurar integrações, tirar dúvidas ou só bater um papo. Estou disponível 24/7!",
    position: "top",
    padding:  10,
    pulse:    true,
  },
];
