export const DEFAULT_LEVELS = [
  { order: 1,  name: "Terra",    requiredPoints: 0,      badgeNumber: 1,  planetEmoji: "🌍" },
  { order: 2,  name: "Lua",      requiredPoints: 100,    badgeNumber: 2,  planetEmoji: "🌙" },
  { order: 3,  name: "Marte",    requiredPoints: 200,    badgeNumber: 3,  planetEmoji: "🔴" },
  { order: 4,  name: "Plutão",   requiredPoints: 300,    badgeNumber: 4,  planetEmoji: "🪨" },
  { order: 5,  name: "Vênus",    requiredPoints: 400,    badgeNumber: 5,  planetEmoji: "🌟" },
  { order: 6,  name: "Júpiter",  requiredPoints: 500,    badgeNumber: 6,  planetEmoji: "🟠" },
  { order: 7,  name: "Saturno",  requiredPoints: 600,    badgeNumber: 7,  planetEmoji: "🪐" },
  { order: 8,  name: "Urano",    requiredPoints: 700,    badgeNumber: 8,  planetEmoji: "🔵" },
  { order: 9,  name: "Netuno",   requiredPoints: 800,    badgeNumber: 9,  planetEmoji: "💙" },
  { order: 10, name: "Mercúrio", requiredPoints: 900,    badgeNumber: 10, planetEmoji: "⚪" },
  { order: 11, name: "Sol",      requiredPoints: 1000,   badgeNumber: 11, planetEmoji: "☀️" },
  { order: 12, name: "Galaxy 1", requiredPoints: 1001,   badgeNumber: 12, planetEmoji: "🌌" },
  { order: 13, name: "Galaxy 2", requiredPoints: 2500,   badgeNumber: 13, planetEmoji: "🌌" },
  { order: 14, name: "Galaxy 3", requiredPoints: 5000,   badgeNumber: 14, planetEmoji: "🌌" },
  { order: 15, name: "Galaxy 4", requiredPoints: 7500,   badgeNumber: 15, planetEmoji: "🌌" },
  { order: 16, name: "Galaxy 5", requiredPoints: 10000,  badgeNumber: 16, planetEmoji: "🌌" },
  { order: 17, name: "Galaxy 6", requiredPoints: 20000,  badgeNumber: 17, planetEmoji: "🌌" },
  { order: 18, name: "Galaxy 7", requiredPoints: 30000,  badgeNumber: 18, planetEmoji: "🌌" },
  { order: 19, name: "Galaxy 8", requiredPoints: 40000,  badgeNumber: 19, planetEmoji: "🌌" },
  { order: 20, name: "Galaxy 9", requiredPoints: 50000,  badgeNumber: 20, planetEmoji: "🌌" },
  { order: 21, name: "Galaxy 10",requiredPoints: 100000, badgeNumber: 21, planetEmoji: "🌌" },
];

export const DEFAULT_RULES = [
  // ── CRÉDITOS (GANHOS) ──────────────────────────────────────────────────────
  { action: "create_lead",               label: "Criar novo lead",                        points:  10,  cooldownHours: null, category: "leads"      },
  { action: "update_lead",               label: "Editar lead",                            points:   3,  cooldownHours: 1,    category: "leads"      },
  { action: "lead_attended_5min",        label: "Atender lead em até 5 min",              points:  25,  cooldownHours: null, category: "leads"      },
  { action: "lead_attended_15min",       label: "Atender lead em até 15 min",             points:  15,  cooldownHours: null, category: "leads"      },
  { action: "lead_won",                  label: "Fechar venda (lead ganho)",              points: 100,  cooldownHours: null, category: "leads"      },
  { action: "lead_recovered",            label: "Recuperar lead perdido",                 points:  50,  cooldownHours: null, category: "leads"      },
  { action: "lead_import_batch",         label: "Importar leads (mín. 10)",               points:  20,  cooldownHours: null, category: "leads"      },
  { action: "move_lead_stage",           label: "Mover lead de estágio",                  points:   5,  cooldownHours: null, category: "leads"      },
  { action: "create_pipeline",           label: "Criar novo pipeline",                    points:  30,  cooldownHours: null, category: "leads"      },
  { action: "pipeline_goal_reached",     label: "Atingir meta do pipeline",               points: 200,  cooldownHours: null, category: "leads"      },
  { action: "automation_created",        label: "Criar automação",                        points:  30,  cooldownHours: null, category: "automation" },
  { action: "automation_100_runs",       label: "Automação executada 100x",               points:  50,  cooldownHours: null, category: "automation" },
  { action: "create_proposal",           label: "Criar proposta",                         points:  15,  cooldownHours: null, category: "forge"      },
  { action: "proposal_viewed",           label: "Proposta visualizada pelo cliente",      points:  10,  cooldownHours: null, category: "forge"      },
  { action: "proposal_accepted",         label: "Proposta aceita pelo cliente",           points:  80,  cooldownHours: null, category: "forge"      },
  { action: "contract_signed",           label: "Contrato assinado",                      points: 100,  cooldownHours: null, category: "forge"      },
  { action: "create_post",               label: "Criar post",                             points:  10,  cooldownHours: null, category: "planner"    },
  { action: "post_published",            label: "Post publicado",                         points:  20,  cooldownHours: null, category: "planner"    },
  { action: "post_approved",             label: "Post aprovado pelo cliente",             points:  30,  cooldownHours: null, category: "planner"    },
  { action: "create_mindmap",            label: "Criar mind map",                         points:  15,  cooldownHours: null, category: "planner"    },
  { action: "complete_monthly_plan",     label: "Completar plano mensal",                 points: 100,  cooldownHours: null, category: "planner"    },
  { action: "ai_command",                label: "Executar comando AI",                    points:   5,  cooldownHours: null, category: "ai"         },
  { action: "create_event",              label: "Criar agendamento",                      points:   8,  cooldownHours: 24,   category: "agenda"     },
  { action: "appointment_done",          label: "Compromisso concluído",                  points:  20,  cooldownHours: null, category: "agenda"     },
  { action: "zero_noshows_monthly",      label: "Zero no-shows no mês",                   points:  50,  cooldownHours: null, category: "agenda"     },
  { action: "form_10_responses",         label: "Receber 10 respostas no formulário",     points:  25,  cooldownHours: null, category: "form"       },
  { action: "form_100_responses",        label: "Receber 100 respostas no formulário",    points: 100,  cooldownHours: null, category: "form"       },
  { action: "upload_nbox",               label: "Upload de arquivo no N.Box",             points:   5,  cooldownHours: 2,    category: "nbox"       },
  { action: "complete_card",             label: "Concluir card",                          points:  10,  cooldownHours: null, category: "workspace"  },
  { action: "complete_10_cards_day",     label: "Concluir 10 cards no dia",               points:  50,  cooldownHours: 24,   category: "workspace"  },
  { action: "chat_reply_2min",           label: "Responder cliente em até 2 min",         points:  15,  cooldownHours: null, category: "chat"       },
  { action: "first_chat_day",            label: "Primeiro atendimento do dia",            points:   5,  cooldownHours: 24,   category: "chat"       },
  { action: "connect_integration",       label: "Conectar nova integração",               points:  50,  cooldownHours: null, category: "integration"},
  { action: "generate_report",           label: "Gerar e compartilhar relatório",         points:  15,  cooldownHours: null, category: "insights"   },
  { action: "login_streak_7days",        label: "Login consecutivo 7 dias",               points:  30,  cooldownHours: null, category: "system"     },
  { action: "login_streak_30days",       label: "Login consecutivo 30 dias",              points: 150,  cooldownHours: null, category: "system"     },
  { action: "weekly_goal_reached",       label: "Meta semanal batida",                    points: 100,  cooldownHours: null, category: "system"     },
  { action: "level_up",                  label: "Subir de nível",                         points: 200,  cooldownHours: null, category: "system"     },
  { action: "onboarding_complete",       label: "Onboarding completo",                    points: 500,  cooldownHours: null, category: "system"     },
  { action: "referral_activated",        label: "Indicar novo cliente ativado",           points: 300,  cooldownHours: null, category: "system"     },
  // ── DÉBITOS / PENALIDADES ─────────────────────────────────────────────────
  { action: "penalty_absent_day2",          label: "⚠️ Ausência: sem login por 2 dias",           points: -10,  cooldownHours: 24,   category: "penalty" },
  { action: "penalty_absent_day3",          label: "⚠️ Ausência: sem login por 3 dias",           points: -15,  cooldownHours: 24,   category: "penalty" },
  { action: "penalty_absent_day7plus",      label: "⚠️ Ausência: sem login 7+ dias (por dia)",    points: -20,  cooldownHours: 24,   category: "penalty" },
  { action: "penalty_demand_overdue",       label: "⚠️ Demanda não finalizada no prazo",          points: -25,  cooldownHours: null, category: "penalty" },
  { action: "penalty_demand_24h",           label: "⚠️ Demanda vencida > 24h sem ação",           points: -50,  cooldownHours: null, category: "penalty" },
  { action: "penalty_3_overdue_day",        label: "⚠️ 3 demandas vencidas no mesmo dia",         points: -100, cooldownHours: 24,   category: "penalty" },
  { action: "penalty_chat_10min",           label: "⚠️ Cliente esperando > 10 min no chat",       points: -15,  cooldownHours: null, category: "penalty" },
  { action: "penalty_chat_30min",           label: "⚠️ Cliente esperando > 30 min no chat",       points: -30,  cooldownHours: null, category: "penalty" },
  { action: "penalty_chat_abandoned",       label: "⚠️ Conversa encerrada sem atendimento",       points: -50,  cooldownHours: null, category: "penalty" },
  { action: "penalty_negative_rating",      label: "⚠️ Avaliação negativa do cliente",            points: -25,  cooldownHours: null, category: "penalty" },
  { action: "penalty_ai_over_120pct",       label: "⚠️ Uso de IA acima de 120% do limite",        points: -25,  cooldownHours: 24,   category: "penalty" },
  { action: "penalty_ai_over_150pct",       label: "⚠️ Uso de IA acima de 150% do limite",        points: -50,  cooldownHours: 24,   category: "penalty" },
  { action: "penalty_proposal_error",       label: "⚠️ Proposta enviada com erro de dados",       points: -10,  cooldownHours: null, category: "penalty" },
  { action: "penalty_contract_cancelled",   label: "⚠️ Contrato cancelado por inadimplência",     points: -30,  cooldownHours: null, category: "penalty" },
  { action: "penalty_lead_lost_nofollowup", label: "⚠️ Lead marcado como perdido sem follow-up",  points: -15,  cooldownHours: null, category: "penalty" },
  // ── CAMPAIGN PLANNER ─────────────────────────────────────────────────────
  { action: "create_campaign_planner",      label: "Criar Planejamento de Campanha",               points: 100,  cooldownHours: null, category: "campaign" },
  { action: "create_campaign_event",        label: "Agendar Evento de Campanha",                   points: 20,   cooldownHours: null, category: "campaign" },
  { action: "upload_brand_asset",           label: "Salvar Material de Marca",                     points: 15,   cooldownHours: null, category: "campaign" },
  { action: "create_campaign_task",         label: "Criar Demanda no Planejamento",                points: 10,   cooldownHours: null, category: "campaign" },
  { action: "complete_campaign_onboarding", label: "Concluir Onboarding de Campanha",              points: 200,  cooldownHours: null, category: "campaign" },
  { action: "share_campaign_calendar",      label: "Compartilhar Calendário da Campanha",          points: 25,   cooldownHours: null, category: "campaign" },
  { action: "complete_campaign",            label: "Concluir Campanha",                            points: 300,  cooldownHours: null, category: "campaign" },
];

export const CATEGORY_LABEL: Record<string, string> = {
  leads:       "CRM / Leads & Tracking",
  forge:       "Forge",
  automation:  "Workflows & Automações",
  planner:     "NASA Planner",
  campaign:    "NASA Campaign Planner",
  ai:          "NASA Command (IA)",
  agenda:      "Agenda",
  workspace:   "Workspace",
  form:        "Formulários",
  nbox:        "N.Box",
  chat:        "Chat & Mensagens",
  integration: "Integrações",
  insights:    "Analytics & Insights",
  system:      "Sistema / Engajamento",
  penalty:     "⚠️ Penalidades",
  custom:      "Personalizada",
};
