export const ALL_APPS: {
  slug: string;
  name: string;
  icon: string;
  category: string;
  cost: number;
  desc: string;
}[] = [
  // Mensageiros
  {
    slug: "whatsapp-business",
    name: "WhatsApp Business",
    icon: "💬",
    category: "Mensageiros",
    cost: 80,
    desc: "Capture leads e gerencie conversas WA no CRM",
  },
  {
    slug: "instagram-dm",
    name: "Instagram DM",
    icon: "📸",
    category: "Mensageiros",
    cost: 60,
    desc: "DMs do Instagram integradas ao pipeline",
  },
  {
    slug: "telegram",
    name: "Telegram",
    icon: "✈️",
    category: "Mensageiros",
    cost: 40,
    desc: "Bots e canais Telegram → leads automáticos",
  },
  {
    slug: "facebook-messenger",
    name: "Facebook Messenger",
    icon: "💙",
    category: "Mensageiros",
    cost: 60,
    desc: "Messenger do Facebook integrado ao CRM",
  },
  {
    slug: "tiktok",
    name: "TikTok",
    icon: "🎵",
    category: "Mensageiros",
    cost: 50,
    desc: "Leads e mensagens TikTok Business no ÓRBITA",
  },
  {
    slug: "linkedin",
    name: "LinkedIn",
    icon: "💼",
    category: "Mensageiros",
    cost: 50,
    desc: "Conexões e DMs do LinkedIn no pipeline",
  },
  {
    slug: "slack",
    name: "Slack",
    icon: "🟦",
    category: "Mensageiros",
    cost: 30,
    desc: "Alertas e notificações no workspace Slack",
  },
  {
    slug: "discord",
    name: "Discord",
    icon: "🎮",
    category: "Mensageiros",
    cost: 30,
    desc: "Servidores Discord → captura de leads",
  },
  // CRM
  {
    slug: "kommo",
    name: "Kommo",
    icon: "🤝",
    category: "CRM & Vendas",
    cost: 60,
    desc: "Sincronize leads entre Kommo e ÓRBITA",
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    icon: "🟠",
    category: "CRM & Vendas",
    cost: 80,
    desc: "Contatos, pipelines e automações HubSpot",
  },
  {
    slug: "salesforce",
    name: "Salesforce",
    icon: "☁️",
    category: "CRM & Vendas",
    cost: 100,
    desc: "Sync em tempo real Salesforce ↔ ÓRBITA",
  },
  {
    slug: "pipedrive",
    name: "Pipedrive",
    icon: "🔵",
    category: "CRM & Vendas",
    cost: 60,
    desc: "Negócios do Pipedrive no pipeline ÓRBITA",
  },
  {
    slug: "rd-station",
    name: "RD Station CRM",
    icon: "🟢",
    category: "CRM & Vendas",
    cost: 60,
    desc: "Leads e funil RD Station sincronizados",
  },
  {
    slug: "agendor",
    name: "Agendor",
    icon: "📋",
    category: "CRM & Vendas",
    cost: 40,
    desc: "Migre dados do Agendor para o ÓRBITA",
  },
  {
    slug: "piperun",
    name: "Piperun",
    icon: "🔄",
    category: "CRM & Vendas",
    cost: 40,
    desc: "Negócios Piperun integrados ao ÓRBITA",
  },
  // Marketing
  {
    slug: "meta-ads",
    name: "Meta Ads",
    icon: "📢",
    category: "Marketing",
    cost: 40,
    desc: "Leads Facebook/Instagram Ads → pipeline",
  },
  {
    slug: "google-ads",
    name: "Google Ads",
    icon: "🎯",
    category: "Marketing",
    cost: 40,
    desc: "Leads Google Ads com rastreamento ÓRBITA",
  },
  {
    slug: "rd-station-mkt",
    name: "RD Station Mkt",
    icon: "📣",
    category: "Marketing",
    cost: 50,
    desc: "Fluxos de automação de marketing",
  },
  {
    slug: "active-campaign",
    name: "ActiveCampaign",
    icon: "📬",
    category: "Marketing",
    cost: 50,
    desc: "E-mail marketing e segmentação integrada",
  },
  {
    slug: "mailchimp",
    name: "Mailchimp",
    icon: "🐒",
    category: "Marketing",
    cost: 30,
    desc: "Campanhas Mailchimp → leads ÓRBITA",
  },
  {
    slug: "leadlovers",
    name: "Leadlovers",
    icon: "🎣",
    category: "Marketing",
    cost: 40,
    desc: "Funis Leadlovers no CRM e pipeline",
  },
  // IA
  {
    slug: "openai",
    name: "OpenAI / ChatGPT",
    icon: "🤖",
    category: "IA & Automação",
    cost: 60,
    desc: "GPT-4 potencializando o ASTRO",
  },
  {
    slug: "google-gemini",
    name: "Google Gemini",
    icon: "✨",
    category: "IA & Automação",
    cost: 50,
    desc: "Gemini para análises multimodais",
  },
  {
    slug: "anthropic",
    name: "Anthropic Claude",
    icon: "🧠",
    category: "IA & Automação",
    cost: 60,
    desc: "Claude para contextos profundos",
  },
  {
    slug: "zapier",
    name: "Zapier",
    icon: "⚡",
    category: "IA & Automação",
    cost: 50,
    desc: "Automatize entre ÓRBITA e +5.000 apps",
  },
  {
    slug: "make",
    name: "Make",
    icon: "🔧",
    category: "IA & Automação",
    cost: 50,
    desc: "Fluxos complexos entre ÓRBITA e centenas de tools",
  },
  {
    slug: "n8n",
    name: "n8n",
    icon: "🔀",
    category: "IA & Automação",
    cost: 40,
    desc: "Automações self-hosted ilimitadas",
  },
  // Pagamentos
  {
    slug: "stripe",
    name: "Stripe",
    icon: "💳",
    category: "Pagamentos",
    cost: 30,
    desc: "Pagamentos internacionais e assinaturas",
  },
  {
    slug: "asaas",
    name: "Asaas",
    icon: "🏦",
    category: "Pagamentos",
    cost: 30,
    desc: "PIX, boleto e cartão integrado ao FORGE",
  },
  {
    slug: "mercado-pago",
    name: "Mercado Pago",
    icon: "💰",
    category: "Pagamentos",
    cost: 40,
    desc: "Pagamentos Mercado Pago no CRM",
  },
  {
    slug: "hotmart",
    name: "Hotmart",
    icon: "🔥",
    category: "Pagamentos",
    cost: 40,
    desc: "Compras Hotmart → leads automáticos",
  },
  {
    slug: "pagseguro",
    name: "PagSeguro",
    icon: "💵",
    category: "Pagamentos",
    cost: 40,
    desc: "Cobranças PagSeguro no pipeline ÓRBITA",
  },
  // Formulários
  {
    slug: "typeform",
    name: "Typeform",
    icon: "📝",
    category: "Formulários",
    cost: 20,
    desc: "Formulários Typeform → leads qualificados",
  },
  {
    slug: "google-forms",
    name: "Google Forms",
    icon: "📋",
    category: "Formulários",
    cost: 20,
    desc: "Google Forms → leads no CRM",
  },
  {
    slug: "jotform",
    name: "JotForm",
    icon: "📄",
    category: "Formulários",
    cost: 20,
    desc: "Respostas JotForm → funil de vendas",
  },
  {
    slug: "tally",
    name: "Tally",
    icon: "🗂️",
    category: "Formulários",
    cost: 15,
    desc: "Forms Tally → leads automáticos",
  },
  // Analytics
  {
    slug: "google-analytics",
    name: "Google Analytics",
    icon: "📊",
    category: "Analytics",
    cost: 20,
    desc: "GA4 correlacionado ao funil de vendas",
  },
  {
    slug: "hotjar",
    name: "Hotjar",
    icon: "🔥",
    category: "Analytics",
    cost: 30,
    desc: "Comportamento de usuários × leads gerados",
  },
  {
    slug: "looker-studio",
    name: "Looker Studio",
    icon: "🔭",
    category: "Analytics",
    cost: 20,
    desc: "Dashboards ÓRBITA no Looker Studio",
  },
  // E-Commerce
  {
    slug: "shopify",
    name: "Shopify",
    icon: "🛍️",
    category: "E-Commerce",
    cost: 80,
    desc: "Pedidos Shopify → leads no CRM",
  },
  {
    slug: "woocommerce",
    name: "WooCommerce",
    icon: "🛒",
    category: "E-Commerce",
    cost: 60,
    desc: "Compras WooCommerce no pipeline",
  },
  {
    slug: "nuvemshop",
    name: "Nuvemshop",
    icon: "☁️",
    category: "E-Commerce",
    cost: 60,
    desc: "Pedidos Nuvemshop → funil ÓRBITA",
  },
  {
    slug: "mercado-livre",
    name: "Mercado Livre",
    icon: "🟡",
    category: "E-Commerce",
    cost: 60,
    desc: "Compradores ML → CRM automático",
  },
  // Assinatura Digital
  {
    slug: "docusign",
    name: "DocuSign",
    icon: "✍️",
    category: "Doc. Digital",
    cost: 40,
    desc: "Contratos DocuSign pelo FORGE",
  },
  {
    slug: "clicksign",
    name: "ClickSign",
    icon: "✅",
    category: "Doc. Digital",
    cost: 40,
    desc: "Assinatura digital brasileira no FORGE",
  },
  {
    slug: "d4sign",
    name: "D4Sign",
    icon: "📜",
    category: "Doc. Digital",
    cost: 30,
    desc: "Documentos com validade jurídica",
  },
  {
    slug: "google-drive",
    name: "Google Drive",
    icon: "📁",
    category: "Doc. Digital",
    cost: 20,
    desc: "Drive sincronizado com o N.Box",
  },
  // Produtividade
  {
    slug: "google-workspace",
    name: "Google Workspace",
    icon: "🏢",
    category: "Produtividade",
    cost: 30,
    desc: "Gmail, Calendar e Drive integrados",
  },
  {
    slug: "microsoft-365",
    name: "Microsoft 365",
    icon: "💻",
    category: "Produtividade",
    cost: 30,
    desc: "Outlook, Teams e OneDrive no ÓRBITA",
  },
  {
    slug: "zoom",
    name: "Zoom",
    icon: "📹",
    category: "Produtividade",
    cost: 30,
    desc: "Reuniões Zoom vinculadas a leads",
  },
  {
    slug: "calendly",
    name: "Calendly",
    icon: "📅",
    category: "Produtividade",
    cost: 20,
    desc: "Agendamentos Calendly na Agenda ÓRBITA",
  },
];

export const APP_CATEGORIES = [...new Set(ALL_APPS.map((a) => a.category))];
